name: ' Publish To AppSource'

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: App version to deliver to AppSource (current, prerelease, draft, latest or version number)
        required: false
        default: 'current'
      projects:
        description: Projects to publish to AppSource if the repository is multi-project. Default is *, which will publish all projects to AppSource.
        required: false
        default: '*'
      GoLive:
        description: Promote AppSource App to go live if it passes technical validation?
        type: boolean
        default: false

permissions:
  contents: read
  actions: read

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Initialization:
    needs: [ ]
    runs-on: [ bc-build ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Dump Workflow Information
        uses: freddydk/AL-Go/Actions/DumpWorkflowInfo@nuget
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go/Actions/WorkflowInitialize@nuget
        with:
          shell: powershell
          eventId: "DO0103"

  Deliver:
    needs: [ Initialization ]
    runs-on: [ bc-build ]
    name: Deliver to AppSource
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read settings
        uses: freddydk/AL-Go/Actions/ReadSettings@nuget
        with:
          shell: powershell

      - name: Read secrets
        id: ReadSecrets
        uses: freddydk/AL-Go/Actions/ReadSecrets@nuget
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'appSourceContext'

      - name: Deliver
        uses: freddydk/AL-Go/Actions/Deliver@nuget
        env:
          Secrets: '${{ steps.ReadSecrets.outputs.Secrets }}'
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          type: 'Release'
          projects: ${{ github.event.inputs.projects }}
          deliveryTarget: 'AppSource'
          artifacts: ${{ github.event.inputs.appVersion }}
          goLive: ${{ github.event.inputs.goLive }}

  PostProcess:
    needs: [ Initialization, Deliver ]
    if: always()
    runs-on: [ bc-build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Finalize the workflow
        id: PostProcess
        uses: freddydk/AL-Go/Actions/WorkflowPostProcess@nuget
        with:
          shell: powershell
          eventId: "DO0103"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
